// Code generated by MockGen. DO NOT EDIT.
// Source: ./customer_service_interface.go
//
// Generated by this command:
//
//	mockgen -destination=./mock/customer_service_mock.go -package=mock -source=./customer_service_interface.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	customer "github.com/stefanowiczd/ddd-case-01/internal/domain/customer"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomerQueryRepository is a mock of CustomerQueryRepository interface.
type MockCustomerQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerQueryRepositoryMockRecorder is the mock recorder for MockCustomerQueryRepository.
type MockCustomerQueryRepositoryMockRecorder struct {
	mock *MockCustomerQueryRepository
}

// NewMockCustomerQueryRepository creates a new mock instance.
func NewMockCustomerQueryRepository(ctrl *gomock.Controller) *MockCustomerQueryRepository {
	mock := &MockCustomerQueryRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerQueryRepository) EXPECT() *MockCustomerQueryRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockCustomerQueryRepository) FindByID(ctx context.Context, id uuid.UUID) (*customer.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*customer.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCustomerQueryRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCustomerQueryRepository)(nil).FindByID), ctx, id)
}

// MockCustomerEventRepository is a mock of CustomerEventRepository interface.
type MockCustomerEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerEventRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerEventRepositoryMockRecorder is the mock recorder for MockCustomerEventRepository.
type MockCustomerEventRepositoryMockRecorder struct {
	mock *MockCustomerEventRepository
}

// NewMockCustomerEventRepository creates a new mock instance.
func NewMockCustomerEventRepository(ctrl *gomock.Controller) *MockCustomerEventRepository {
	mock := &MockCustomerEventRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerEventRepository) EXPECT() *MockCustomerEventRepositoryMockRecorder {
	return m.recorder
}

// CreateEvents mocks base method.
func (m *MockCustomerEventRepository) CreateEvents(ctx context.Context, events []customer.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvents", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEvents indicates an expected call of CreateEvents.
func (mr *MockCustomerEventRepositoryMockRecorder) CreateEvents(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvents", reflect.TypeOf((*MockCustomerEventRepository)(nil).CreateEvents), ctx, events)
}
