// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: account_query.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, customer_id, account_number, balance, currency, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, account_number, customer_id, balance, currency, status, created_at, updated_at
`

type CreateAccountParams struct {
	ID            pgtype.UUID
	CustomerID    pgtype.UUID
	AccountNumber string
	Balance       float64
	Currency      string
	Status        string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.CustomerID,
		arg.AccountNumber,
		arg.Balance,
		arg.Currency,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountNumber,
		&i.CustomerID,
		&i.Balance,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const depositAccountMoney = `-- name: DepositAccountMoney :exec
UPDATE accounts
SET balance = balance + $2
WHERE id = $1
`

type DepositAccountMoneyParams struct {
	ID      pgtype.UUID
	Balance float64
}

func (q *Queries) DepositAccountMoney(ctx context.Context, arg DepositAccountMoneyParams) error {
	_, err := q.db.Exec(ctx, depositAccountMoney, arg.ID, arg.Balance)
	return err
}

const findAccountByID = `-- name: FindAccountByID :one
SELECT id, account_number, customer_id, balance, currency, status, created_at, updated_at FROM accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) FindAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, findAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountNumber,
		&i.CustomerID,
		&i.Balance,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAccountsByCustomerID = `-- name: FindAccountsByCustomerID :many
SELECT id, account_number, customer_id, balance, currency, status, created_at, updated_at FROM accounts
WHERE customer_id = $1
`

func (q *Queries) FindAccountsByCustomerID(ctx context.Context, customerID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, findAccountsByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.AccountNumber,
			&i.CustomerID,
			&i.Balance,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountStatus = `-- name: UpdateAccountStatus :exec
UPDATE accounts
SET status = $2
WHERE id = $1
`

type UpdateAccountStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error {
	_, err := q.db.Exec(ctx, updateAccountStatus, arg.ID, arg.Status)
	return err
}

const withdrawAccountMoney = `-- name: WithdrawAccountMoney :exec
UPDATE accounts
SET balance = balance - $2
WHERE id = $1
`

type WithdrawAccountMoneyParams struct {
	ID      pgtype.UUID
	Balance float64
}

func (q *Queries) WithdrawAccountMoney(ctx context.Context, arg WithdrawAccountMoneyParams) error {
	_, err := q.db.Exec(ctx, withdrawAccountMoney, arg.ID, arg.Balance)
	return err
}
