// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            pgtype.UUID
	AccountNumber string
	CustomerID    pgtype.UUID
	Balance       float64
	Currency      string
	Status        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type AccountEvent struct {
	ID               pgtype.UUID
	AccountID        pgtype.UUID
	EventType        string
	EventTypeVersion string
	EventState       string
	CreatedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	ScheduledAt      pgtype.Timestamptz
	Retry            int32
	MaxRetry         int32
	EventData        []byte
}

type Customer struct {
	ID             pgtype.UUID
	FirstName      string
	LastName       string
	Email          string
	Phone          pgtype.Text
	DateOfBirth    pgtype.Date
	AddressStreet  pgtype.Text
	AddressCity    pgtype.Text
	AddressState   pgtype.Text
	AddressZipCode pgtype.Text
	AddressCountry pgtype.Text
	Status         string
	DeletedAt      pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}
