// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID               pgtype.UUID
	ContextID        pgtype.UUID
	EventOrigin      string
	EventType        string
	EventTypeVersion string
	EventState       string
	CreatedAt        pgtype.Timestamp
	ScheduledAt      pgtype.Timestamp
	StartedAt        pgtype.Timestamp
	CompletedAt      pgtype.Timestamp
	Retry            int32
	MaxRetry         int32
	EventData        []byte
}
